### ISSUE TITLE
Add Effort controller for Freddy Arms

### ISSUE THREAD

**Issue by arunimaCh29** [HBRS-SDP/ss24-gazebo-simulation-freddy#16]
While Position and velocity controller are working for Freddy's arms, add effort controller to send torque commands to the joints in the arms.

**Comment by ShinasShaji** [comment]
Complete with commit [fe3516e](https://github.com/HBRS-SDP/ss24-gazebo-simulation-freddy/commit/fe3516e8bbfb9f072d6dc76a00e77f091a571982)
