### ISSUE TITLE
Create Documentation for the steps followed and issues faced as FAQ's

### ISSUE THREAD

**Issue by arunimaCh29** [HBRS-SDP/ss24-gazebo-simulation-freddy#9]
As a project maintainer, i want up to date documentation of the robot's simulation and the steps required to get it working for basic movements. I also want a documentation maintained for all the issues faced while developing the solution, for future references of issues.

**Comment by ShinasShaji** [comment]
This includes:
- The ROS2 control tags in the Kinova description could not be overloaded with tags in Freddy's description
- The inability to load a controller before the previous controller was unloaded
- Self collision is disabled by default, which means parts of the robot can clip into each other
- No friction or damping was defined for the Robile base's drives, which meant that a motion given to these wheels would continue indefinitely
- Some inertial volumes of the robot can cause the robot to topple over. While this was initially noted in the absence of Freddy's arms, this needs to be investigated to find out whether the problem persists

**Comment by arunimaCh29** [comment]
Added to the final presentation
